### ISSUE TITLE
fail building

### ISSUE THREAD

**Issue by aion-chris** [aionnetwork/aionr#70]
> os & version: ubuntu 18.04
> branch: dev_unity
> action: cargo build --release
---------------------------------------------------------------------------
error: failed to run custom build command for `avm v0.2.0 (file:///root/aionr/vms/avm)`
process didn't exit successfully: `/root/aionr/target/release/build/avm-4208619851e630fc/build-script-build` (exit code: 101)
--- stdout
make: Entering directory '/root/aionr/vms/avm/libs/native_loader/native'
Compiling org_aion_avm_loader_Loader.cpp
Generating /root/aionr/target/release/build/avm-3140baf2639f3711/out/libavmloader.so
make: Leaving directory '/root/aionr/vms/avm/libs/native_loader/native'

--- stderr
thread 'main' panicked at 'failed to build native loader: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...

**Comment by r3gata** [comment]
May I ask what the resolution ended up being for this issue?
